apiVersion: v1
kind: Service
metadata:
  name: link-shortener
spec:
  type: NodePort
  selector:
    app: link-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31358
