apiVersion: batch/v1
kind: Job
metadata:
  name: link-shortener-test
spec:
  template:
    spec:
      containers:
      - name: link-shortener-test
        image: link-shortener:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "go test ./..."]
        env:
        - name: REDIS_ADDR
          value: "redis:6379"  # Kubernetes içindeki Redis servisi adresi
      restartPolicy: Never
  backoffLimit: 1
